### ISSUE TITLE
[Question] OpenAI

### ISSUE THREAD

**Issue by Sau1707** [afterpartyai/bittensor-conversation-genome-project#6]
Hello, I was wondering why it's used an embedding model from openai and not an open souce one, furthermore if all the miners use the embedding of openai, why creating a subnet to do that and don't make this "in-house".

**Comment by afterpartyjohn** [comment]
Hey There! We standardized the OpenAI embedding model for the launch of the subnet, however we are exploring ways of opening up the embedding layer to accommodate any model that miners want to use. 

We created this subnet to enable decentralized contribution to the largest open-source, annotated, conversational dataset in history. This will allow research and training of next-gen conversational AI.
